go-jet/jet

qrm/utill.go
tests/postgres/sample_test.go

When using a UUID as a primary key with PostgreSQL the grouping was
defaulting to the row which caused incorrect results to be returned.

Fix issue with using UUID primary keys in complex return types

---

mysql/delete_statement.go
mysql/select_statement.go
mysql/set_statement.go
mysql/types.go
postgres/select_statement.go
postgres/set_statement.go
postgres/types.go

enables e.g. creating a collection of clauses beforehand and dynamically adding to it.
this resolves #48.

export OrderByClause type through alias

---

internal/jet/func_expression.go
internal/jet/func_expression_test.go
mysql/expressions.go
postgres/expressions.go

This allows expressions like jet.Func("FOO", String("test")) to be
emitted as FOO($1).

Add support for custom functions.

---

qrm/utill.go

PR based on your decimal branch that is backward compatible with existing generated models that uses the float64 type. All the postgres tests are passing. This may breaks custom models that defined their own decimal type but paradoxically this may be a good thing if they cares about decimal precision.

lossless decimal type with float64 backward compatibility

---

generator/internal/template/templates.go
internal/jet/table.go
internal/jet/table_test.go

Resolves #46
- Support for renaming table schemas
* Table support for renaming schema
* Empty schema name is left out (using default schema for the
database connection)
* Generated code support for obtaining a version of the table with
renamed schema, similarly as the `AS` function works
* Unit tests for setting and clearing the schema name

Schema rename support

---

cmd/jet/main.go
generator/mysql/mysql_generator.go
generator/postgres/postgres_generator.go
go.mod
go.sum
tests/init/init.go
tests/mysql/generator_test.go
tests/postgres/generator_test.go

Allow to connect via DSN https://github.com/go-jet/jet/issues/88. For postgresql and mysql generators.
Added not required parameter `-dsn`. When this new flag is provided, all other connection flags is ignored. It tries to detect source by connection string, specially by `scheme` prefix. 
If string provided without `scheme` (e.g. `postgresql://`, `mysql://`, etc.), `-source` flag is required.
```sh
$ jet -source=PostgreSQL -host=localhost -port=5432 -user=postgres -password="" -dbname=service # old-way
$ jet -dsn=postgresql://postgres@localhost:5432/service # postgres
$ jet -source=MySQL -dsn=root@tcp(localhost:3306)/service # mysql
$ jet -dsn=mysql://root@tcp(localhost:3306)/service # mysql 2
```
Docs for DSN: [PostgreSQL](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-C …

Connection via DSN

---

postgres/literal.go
postgres/literal_test.go

Json types are crucial for postgres. This PR add support to easily cast golang string as postgres json type.
Solves https://github.com/go-jet/jet/issues/160.

Add postgres json literal

---

internal/jet/column_types.go

it has been already implemented, just missing from interface

add missing SET method to ColumnTimez interface

---

postgres/dialect.go

https://www.postgresql.org/docs/current/sql-keywords-appendix.html
Seems like reserved word "RIGHT" omitted in the `reservedWords` in the postgresql dialect

fix: Add omitted reserved word 'RIGHT' on postgresql

---

generator/mysql/mysql_generator.go
generator/postgres/postgres_generator.go

I am using go-jet as a go library for an application that uses dynamic database credentials and noticed this potential security risk that exposes the whole database credentials (though it is timed, it is still a risk)

Potential security flaw

---

go.mod
go.sum
qrm/scan_context.go
tests/postgres/select_test.go

See #198 
The change is quite simple. We check if the field is tagged as primary key, if so, we add it as an index regardless of its type.

Allow custom types as indexes when joining tables

---

generator/template/file_templates.go
generator/template/sql_builder_template.go
tests/mysql/generator_template_test.go
tests/postgres/generator_template_test.go

The following code
```
func generateJetTypes(connectionString string) error {
return jet.GenerateDSN(connectionString, "public", "gen", template.Default(postgres.Dialect).
UseSchema(func(schemaMetaData metadata.Schema) template.Schema {
return template.DefaultSchema(schemaMetaData)
.UseSQLBuilder(template.DefaultSQLBuilder().
UseTable(func(table metadata.Table) template.TableSQLBuilder {
return template.DefaultTableSQLBuilder(table).UseDefaultAlias(strings.Trim(table.Name, "s"))
}))
}))
}
```
generates the following output 
```
(...)
var Users = newUsersTable("public", "users", "user")
type usersTable struct {
(...)
```
for the following table 
```
CREATE TABLE users (
id UUID PRIMARY KEY,
name character varying(45) NOT NULL,
surname character varying(45) NOT NULL,
updated_at timestamp …
```

Add DefaultAlias option to TableSQLBuilder

---

generator/mysql/mysql_generator.go
generator/mysql/query_set.go
go.mod
go.sum

Optimisation consists of two parts:
- faster SQL query
- leverage concurrency
Sample run:
```sh
$ jet -source=mysql -dsn="$MYSQL_USER:$MYSQL_PASS@tcp(localhost:$MYSQL_PORT)/facility" -path=./gen
Connecting to MySQL database...
Retrieving database information...
FOUND 148 table(s), 162 view(s), 13 enum(s)
Destination directory: gen/facility
Cleaning up destination directory...
Generating table model files...
Generating view model files...
Generating enum model files...
Generating table sql builder files
Generating view sql builder files
Generating enum sql builder files
```
Results:
- master: 4m9s
- with improved SQL:  42s
- with improved SQL + concurrency: 21s
Tested with MySQL 5.7 running locally in Docker.

10x mysql db info querying speedup

---

internal/jet/select_lock.go
mysql/select_statement_test.go
postgres/select_statement_test.go
tests/postgres/select_test.go

This adds support for statements such as `SELECT ... FOR UPDATE OF table NOWAIT` where `OF table` could not be specified previously. Fixes #285.

Add support for OF in row lock clauses

---

postgres/clause.go
postgres/clause_test.go

ON CONFLICT DO NOTHING without a conflict target is valid SQL according to Postgres.
https://www.postgresql.org/docs/15/sql-insert.html#SQL-ON-CONFLICT

ON CONFLICT DO NOTHING without a conflict target is valid SQL

---

internal/jet/operators.go
mysql/expressions.go
postgres/expressions.go
sqlite/expressions.go

This PR exports a `BinaryOperator` function that is similar in spirit to `jet.Func`, but for custom/unsupported operators rather than for functions. See https://github.com/go-jet/jet/issues/338
This is kind of a proof-of-concept PR; maybe this should have tests? It should probably have docs as well.
Maybe there should also be a `UnaryOperator` and a `TernaryOperator` but at least from my perspective I don't foresee a huge need for those.

Export BinaryOperator function

---

internal/jet/expression.go
internal/jet/func_expression.go
internal/jet/group_by_clause.go
mysql/expressions.go
postgres/expressions.go
sqlite/expressions.go

Hey Goran, nice lib! I hope you'll consider allowing a change like this. Doing this allows a particular SQL dialect to implement additional operators/expressions that may deviate from default SQL.
Background: I'm playing with a dialect that supports this notation:
SELECT * FROM table WHERE any_match ( x -> x IS NOT NULL, someField )
That'd be something I'd want to implement just for that dialect (in its own dialect package in jet) but for that I need access to the serializer method. 
This pull request has no functional changes, just a refactoring to expose `jet.newCustomExpression` to other jet packages.

feat: export CustomExpression and Token for dialects to use 

---

generator/metadata/column_meta_data.go
generator/mysql/query_set.go
generator/postgres/query_set.go
generator/sqlite/query_set.go
tests/mysql/generator_test.go
tests/postgres/generator_template_test.go
tests/postgres/generator_test.go
tests/sqlite/generator_test.go

Adds a new "HasDefault" field to the column metadata. The field value is `true` if the column has a default value and false otherwise.
Added integration tests for postgres, mysql, and sqlite that assert the value is set as expected. Results are specific to each database.

Add HasDefault column metadata

---

postgres/functions.go
postgres/functions_test.go

Adds the `DATE_TRUNC` function for Postgres.

Add Postgres DATE_TRUNC function

---

internal/jet/column_assigment.go
internal/testutils/test_utils.go
postgres/columns.go
tests/postgres/alltypes_test.go
tests/postgres/insert_test.go
tests/postgres/sample_test.go

Improved support for intervals in postgres

---

generator/template/sql_builder_template.go
generator/template/sql_builder_template_test.go

fixes #408 
- Added a function to rename a column if it conflicts with reserved keywords. 
- Updated sql_builder_template to check if column is in a conflict with reserved key words
- Added unit tests. 
Thank you for this awesome project! Let me know if there is anything I can add or change.

Fix generating schema fails due to column name conflicts

---

postgres/functions.go
postgres/functions_test.go

Adds GENERATE_SERIES function https://www.postgresql.org/docs/current/functions-srf.html
I could also add the GENERATE_SUBSCRIPTS function but it has to wait for array expressions https://github.com/go-jet/jet/pull/380.

Add Postgres GENERATE_SERIES function

---

mysql/update_statement.go
mysql/update_statement_test.go
tests/mysql/update_test.go

feature: Add support for LIMIT query in UPDATE for sql/sqlite

---

generator/template/process.go
internal/utils/filesys/filesys.go

RemoveAll removes path and any children it contains. It removes everything it can but returns the first error it encounters. If the path does not exist, RemoveAll returns nil (no error). If there is an error, it will be of type [*PathError].
So, there is no need to check whether the directory exists.

remove redundant call in filesys RemoveDir

---

generator/template/model_template.go
tests/mysql/generator_template_test.go
tests/postgres/generator_template_test.go

- fix #442
- Since handling all edge cases for generic type parsing is not trivial, users will specify the fields manually.
- To support more than one import per type, add an additional field for extra imports per type.
- Add examples for defining those types in the current tests that show how to define custom types.

Add a field for additional imports when using generic types

---

generator/mysql/query_set.go
tests/mysql/generator_test.go
tests/mysql/sample_test.go

Excluded GENERATED ALWAYS VIRTUAL columns from mutable columns. 
Issue ID: [454](https://github.com/go-jet/jet/issues/454)

Excluded GENERATED ALWAYS VIRTUAL columns from mutable columns

---

cmd/jet/main.go
internal/3rdparty/snaker/snaker.go
internal/3rdparty/snaker/snaker_test.go
tests/postgres/generator_test.go

- Add flag to cmd to allow table/view models to generate json tags using snake, camel, or pascal case.
- Add tests for both table and models and for each casing

add model json tag to args
